### ISSUE TITLE
ResNet width

### ISSUE THREAD

**Issue by vanderschuea** [x-zho14/ProbMask-official#1]
Hi,

The width of your ResNet is **not** correct, the first convolution should output a width of 16 not 32, and all other values should be divided by 2 too. Was this the network structure used to generate the results in the paper? Because if this is the case, the published results are wrong and not comparable to other papers (although I suppose the comparison to STR was re-run and thus the relative comparison inside the paper is nonetheless correct).

Thanks in advance for your response!

**Comment by x-zho14** [comment]
Actually, this configuration of width of ResNet-32 on CIFAR-10/100 is described in appendix, following the setting of [1]. The results of STR are run under the same setting.

[1] Picking Winning Tickets Before Training by Preserving Gradient Flow

**Comment by vanderschuea** [comment]
Indeed, I read the version of the paper w/o the appendix at first and missed this information, thanks for your reply
